apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "stackit-pod-identity-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackit-pod-identity-webhook.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "stackit-pod-identity-webhook.selectorLabels" . | nindent 6 }}
  unhealthyPodEvictionPolicy: AlwaysAllow
