apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stackit-pod-identity-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: stackit-pod-identity-webhook
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stackit-pod-identity-webhook
  unhealthyPodEvictionPolicy: AlwaysAllow
