apiVersion: v1
kind: Service
metadata:
  name: stackit-pod-identity-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: stackit-pod-identity-webhook
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.webhook.port }}
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: stackit-pod-identity-webhook
