//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 */
// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&ControlPlaneConfig{}, func(obj interface{}) { SetObjectDefaults_ControlPlaneConfig(obj.(*ControlPlaneConfig)) })
	scheme.AddTypeDefaultingFunc(&SelfHostedShootExposureConfig{}, func(obj interface{}) {
		SetObjectDefaults_SelfHostedShootExposureConfig(obj.(*SelfHostedShootExposureConfig))
	})
	return nil
}

func SetObjectDefaults_ControlPlaneConfig(in *ControlPlaneConfig) {
	SetDefaults_ControlPlaneConfig(in)
}

func SetObjectDefaults_SelfHostedShootExposureConfig(in *SelfHostedShootExposureConfig) {
	SetDefaults_SelfHostedShootExposureConfig(in)
}
