// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackitcloud/stackit-sdk-go/services/dns/v1api (interfaces: DefaultAPI)
//
// Generated by this command:
//
//	mockgen -destination ./pkg/stackit/client/mock/dns/dns.go -package dns github.com/stackitcloud/stackit-sdk-go/services/dns/v1api DefaultAPI
//

// Package dns is a generated GoMock package.
package dns

import (
	context "context"
	reflect "reflect"

	v1api "github.com/stackitcloud/stackit-sdk-go/services/dns/v1api"
	gomock "go.uber.org/mock/gomock"
)

// MockDefaultAPI is a mock of DefaultAPI interface.
type MockDefaultAPI struct {
	ctrl     *gomock.Controller
	recorder *MockDefaultAPIMockRecorder
	isgomock struct{}
}

// MockDefaultAPIMockRecorder is the mock recorder for MockDefaultAPI.
type MockDefaultAPIMockRecorder struct {
	mock *MockDefaultAPI
}

// NewMockDefaultAPI creates a new mock instance.
func NewMockDefaultAPI(ctrl *gomock.Controller) *MockDefaultAPI {
	mock := &MockDefaultAPI{ctrl: ctrl}
	mock.recorder = &MockDefaultAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDefaultAPI) EXPECT() *MockDefaultAPIMockRecorder {
	return m.recorder
}

// CloneZone mocks base method.
func (m *MockDefaultAPI) CloneZone(ctx context.Context, projectId, zoneId string) v1api.ApiCloneZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneZone", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiCloneZoneRequest)
	return ret0
}

// CloneZone indicates an expected call of CloneZone.
func (mr *MockDefaultAPIMockRecorder) CloneZone(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneZone", reflect.TypeOf((*MockDefaultAPI)(nil).CloneZone), ctx, projectId, zoneId)
}

// CloneZoneExecute mocks base method.
func (m *MockDefaultAPI) CloneZoneExecute(r v1api.ApiCloneZoneRequest) (*v1api.ZoneResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneZoneExecute", r)
	ret0, _ := ret[0].(*v1api.ZoneResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneZoneExecute indicates an expected call of CloneZoneExecute.
func (mr *MockDefaultAPIMockRecorder) CloneZoneExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneZoneExecute", reflect.TypeOf((*MockDefaultAPI)(nil).CloneZoneExecute), r)
}

// CreateLabel mocks base method.
func (m *MockDefaultAPI) CreateLabel(ctx context.Context, projectId, zoneId string) v1api.ApiCreateLabelRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLabel", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiCreateLabelRequest)
	return ret0
}

// CreateLabel indicates an expected call of CreateLabel.
func (mr *MockDefaultAPIMockRecorder) CreateLabel(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLabel", reflect.TypeOf((*MockDefaultAPI)(nil).CreateLabel), ctx, projectId, zoneId)
}

// CreateLabelExecute mocks base method.
func (m *MockDefaultAPI) CreateLabelExecute(r v1api.ApiCreateLabelRequest) (*v1api.CreateLabelResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLabelExecute", r)
	ret0, _ := ret[0].(*v1api.CreateLabelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLabelExecute indicates an expected call of CreateLabelExecute.
func (mr *MockDefaultAPIMockRecorder) CreateLabelExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLabelExecute", reflect.TypeOf((*MockDefaultAPI)(nil).CreateLabelExecute), r)
}

// CreateMoveCode mocks base method.
func (m *MockDefaultAPI) CreateMoveCode(ctx context.Context, projectId, zoneId string) v1api.ApiCreateMoveCodeRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMoveCode", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiCreateMoveCodeRequest)
	return ret0
}

// CreateMoveCode indicates an expected call of CreateMoveCode.
func (mr *MockDefaultAPIMockRecorder) CreateMoveCode(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMoveCode", reflect.TypeOf((*MockDefaultAPI)(nil).CreateMoveCode), ctx, projectId, zoneId)
}

// CreateMoveCodeExecute mocks base method.
func (m *MockDefaultAPI) CreateMoveCodeExecute(r v1api.ApiCreateMoveCodeRequest) (*v1api.MoveCodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMoveCodeExecute", r)
	ret0, _ := ret[0].(*v1api.MoveCodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMoveCodeExecute indicates an expected call of CreateMoveCodeExecute.
func (mr *MockDefaultAPIMockRecorder) CreateMoveCodeExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMoveCodeExecute", reflect.TypeOf((*MockDefaultAPI)(nil).CreateMoveCodeExecute), r)
}

// CreateRecordSet mocks base method.
func (m *MockDefaultAPI) CreateRecordSet(ctx context.Context, projectId, zoneId string) v1api.ApiCreateRecordSetRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecordSet", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiCreateRecordSetRequest)
	return ret0
}

// CreateRecordSet indicates an expected call of CreateRecordSet.
func (mr *MockDefaultAPIMockRecorder) CreateRecordSet(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecordSet", reflect.TypeOf((*MockDefaultAPI)(nil).CreateRecordSet), ctx, projectId, zoneId)
}

// CreateRecordSetExecute mocks base method.
func (m *MockDefaultAPI) CreateRecordSetExecute(r v1api.ApiCreateRecordSetRequest) (*v1api.RecordSetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecordSetExecute", r)
	ret0, _ := ret[0].(*v1api.RecordSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecordSetExecute indicates an expected call of CreateRecordSetExecute.
func (mr *MockDefaultAPIMockRecorder) CreateRecordSetExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecordSetExecute", reflect.TypeOf((*MockDefaultAPI)(nil).CreateRecordSetExecute), r)
}

// CreateZone mocks base method.
func (m *MockDefaultAPI) CreateZone(ctx context.Context, projectId string) v1api.ApiCreateZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateZone", ctx, projectId)
	ret0, _ := ret[0].(v1api.ApiCreateZoneRequest)
	return ret0
}

// CreateZone indicates an expected call of CreateZone.
func (mr *MockDefaultAPIMockRecorder) CreateZone(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateZone", reflect.TypeOf((*MockDefaultAPI)(nil).CreateZone), ctx, projectId)
}

// CreateZoneExecute mocks base method.
func (m *MockDefaultAPI) CreateZoneExecute(r v1api.ApiCreateZoneRequest) (*v1api.ZoneResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateZoneExecute", r)
	ret0, _ := ret[0].(*v1api.ZoneResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateZoneExecute indicates an expected call of CreateZoneExecute.
func (mr *MockDefaultAPIMockRecorder) CreateZoneExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateZoneExecute", reflect.TypeOf((*MockDefaultAPI)(nil).CreateZoneExecute), r)
}

// DeleteLabel mocks base method.
func (m *MockDefaultAPI) DeleteLabel(ctx context.Context, projectId, zoneId, key string) v1api.ApiDeleteLabelRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLabel", ctx, projectId, zoneId, key)
	ret0, _ := ret[0].(v1api.ApiDeleteLabelRequest)
	return ret0
}

// DeleteLabel indicates an expected call of DeleteLabel.
func (mr *MockDefaultAPIMockRecorder) DeleteLabel(ctx, projectId, zoneId, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLabel", reflect.TypeOf((*MockDefaultAPI)(nil).DeleteLabel), ctx, projectId, zoneId, key)
}

// DeleteLabelExecute mocks base method.
func (m *MockDefaultAPI) DeleteLabelExecute(r v1api.ApiDeleteLabelRequest) (*v1api.DeleteLabelResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLabelExecute", r)
	ret0, _ := ret[0].(*v1api.DeleteLabelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLabelExecute indicates an expected call of DeleteLabelExecute.
func (mr *MockDefaultAPIMockRecorder) DeleteLabelExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLabelExecute", reflect.TypeOf((*MockDefaultAPI)(nil).DeleteLabelExecute), r)
}

// DeleteMoveCode mocks base method.
func (m *MockDefaultAPI) DeleteMoveCode(ctx context.Context, projectId, zoneId string) v1api.ApiDeleteMoveCodeRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMoveCode", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiDeleteMoveCodeRequest)
	return ret0
}

// DeleteMoveCode indicates an expected call of DeleteMoveCode.
func (mr *MockDefaultAPIMockRecorder) DeleteMoveCode(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMoveCode", reflect.TypeOf((*MockDefaultAPI)(nil).DeleteMoveCode), ctx, projectId, zoneId)
}

// DeleteMoveCodeExecute mocks base method.
func (m *MockDefaultAPI) DeleteMoveCodeExecute(r v1api.ApiDeleteMoveCodeRequest) (*v1api.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMoveCodeExecute", r)
	ret0, _ := ret[0].(*v1api.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMoveCodeExecute indicates an expected call of DeleteMoveCodeExecute.
func (mr *MockDefaultAPIMockRecorder) DeleteMoveCodeExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMoveCodeExecute", reflect.TypeOf((*MockDefaultAPI)(nil).DeleteMoveCodeExecute), r)
}

// DeleteRecordSet mocks base method.
func (m *MockDefaultAPI) DeleteRecordSet(ctx context.Context, projectId, zoneId, rrSetId string) v1api.ApiDeleteRecordSetRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordSet", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(v1api.ApiDeleteRecordSetRequest)
	return ret0
}

// DeleteRecordSet indicates an expected call of DeleteRecordSet.
func (mr *MockDefaultAPIMockRecorder) DeleteRecordSet(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordSet", reflect.TypeOf((*MockDefaultAPI)(nil).DeleteRecordSet), ctx, projectId, zoneId, rrSetId)
}

// DeleteRecordSetExecute mocks base method.
func (m *MockDefaultAPI) DeleteRecordSetExecute(r v1api.ApiDeleteRecordSetRequest) (*v1api.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordSetExecute", r)
	ret0, _ := ret[0].(*v1api.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRecordSetExecute indicates an expected call of DeleteRecordSetExecute.
func (mr *MockDefaultAPIMockRecorder) DeleteRecordSetExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordSetExecute", reflect.TypeOf((*MockDefaultAPI)(nil).DeleteRecordSetExecute), r)
}

// DeleteZone mocks base method.
func (m *MockDefaultAPI) DeleteZone(ctx context.Context, projectId, zoneId string) v1api.ApiDeleteZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteZone", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiDeleteZoneRequest)
	return ret0
}

// DeleteZone indicates an expected call of DeleteZone.
func (mr *MockDefaultAPIMockRecorder) DeleteZone(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteZone", reflect.TypeOf((*MockDefaultAPI)(nil).DeleteZone), ctx, projectId, zoneId)
}

// DeleteZoneExecute mocks base method.
func (m *MockDefaultAPI) DeleteZoneExecute(r v1api.ApiDeleteZoneRequest) (*v1api.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteZoneExecute", r)
	ret0, _ := ret[0].(*v1api.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteZoneExecute indicates an expected call of DeleteZoneExecute.
func (mr *MockDefaultAPIMockRecorder) DeleteZoneExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteZoneExecute", reflect.TypeOf((*MockDefaultAPI)(nil).DeleteZoneExecute), r)
}

// ExportRecordSets mocks base method.
func (m *MockDefaultAPI) ExportRecordSets(ctx context.Context, projectId, zoneId string) v1api.ApiExportRecordSetsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportRecordSets", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiExportRecordSetsRequest)
	return ret0
}

// ExportRecordSets indicates an expected call of ExportRecordSets.
func (mr *MockDefaultAPIMockRecorder) ExportRecordSets(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportRecordSets", reflect.TypeOf((*MockDefaultAPI)(nil).ExportRecordSets), ctx, projectId, zoneId)
}

// ExportRecordSetsExecute mocks base method.
func (m *MockDefaultAPI) ExportRecordSetsExecute(r v1api.ApiExportRecordSetsRequest) (*v1api.ZoneDataExchange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportRecordSetsExecute", r)
	ret0, _ := ret[0].(*v1api.ZoneDataExchange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportRecordSetsExecute indicates an expected call of ExportRecordSetsExecute.
func (mr *MockDefaultAPIMockRecorder) ExportRecordSetsExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportRecordSetsExecute", reflect.TypeOf((*MockDefaultAPI)(nil).ExportRecordSetsExecute), r)
}

// GetRecordSet mocks base method.
func (m *MockDefaultAPI) GetRecordSet(ctx context.Context, projectId, zoneId, rrSetId string) v1api.ApiGetRecordSetRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordSet", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(v1api.ApiGetRecordSetRequest)
	return ret0
}

// GetRecordSet indicates an expected call of GetRecordSet.
func (mr *MockDefaultAPIMockRecorder) GetRecordSet(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordSet", reflect.TypeOf((*MockDefaultAPI)(nil).GetRecordSet), ctx, projectId, zoneId, rrSetId)
}

// GetRecordSetExecute mocks base method.
func (m *MockDefaultAPI) GetRecordSetExecute(r v1api.ApiGetRecordSetRequest) (*v1api.RecordSetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordSetExecute", r)
	ret0, _ := ret[0].(*v1api.RecordSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordSetExecute indicates an expected call of GetRecordSetExecute.
func (mr *MockDefaultAPIMockRecorder) GetRecordSetExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordSetExecute", reflect.TypeOf((*MockDefaultAPI)(nil).GetRecordSetExecute), r)
}

// GetZone mocks base method.
func (m *MockDefaultAPI) GetZone(ctx context.Context, projectId, zoneId string) v1api.ApiGetZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZone", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiGetZoneRequest)
	return ret0
}

// GetZone indicates an expected call of GetZone.
func (mr *MockDefaultAPIMockRecorder) GetZone(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZone", reflect.TypeOf((*MockDefaultAPI)(nil).GetZone), ctx, projectId, zoneId)
}

// GetZoneExecute mocks base method.
func (m *MockDefaultAPI) GetZoneExecute(r v1api.ApiGetZoneRequest) (*v1api.ZoneResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZoneExecute", r)
	ret0, _ := ret[0].(*v1api.ZoneResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZoneExecute indicates an expected call of GetZoneExecute.
func (mr *MockDefaultAPIMockRecorder) GetZoneExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZoneExecute", reflect.TypeOf((*MockDefaultAPI)(nil).GetZoneExecute), r)
}

// ImportRecordSets mocks base method.
func (m *MockDefaultAPI) ImportRecordSets(ctx context.Context, projectId, zoneId string) v1api.ApiImportRecordSetsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportRecordSets", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiImportRecordSetsRequest)
	return ret0
}

// ImportRecordSets indicates an expected call of ImportRecordSets.
func (mr *MockDefaultAPIMockRecorder) ImportRecordSets(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportRecordSets", reflect.TypeOf((*MockDefaultAPI)(nil).ImportRecordSets), ctx, projectId, zoneId)
}

// ImportRecordSetsExecute mocks base method.
func (m *MockDefaultAPI) ImportRecordSetsExecute(r v1api.ApiImportRecordSetsRequest) (*v1api.ImportRecordSetsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportRecordSetsExecute", r)
	ret0, _ := ret[0].(*v1api.ImportRecordSetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportRecordSetsExecute indicates an expected call of ImportRecordSetsExecute.
func (mr *MockDefaultAPIMockRecorder) ImportRecordSetsExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportRecordSetsExecute", reflect.TypeOf((*MockDefaultAPI)(nil).ImportRecordSetsExecute), r)
}

// ListLabels mocks base method.
func (m *MockDefaultAPI) ListLabels(ctx context.Context, projectId, zoneId string) v1api.ApiListLabelsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLabels", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiListLabelsRequest)
	return ret0
}

// ListLabels indicates an expected call of ListLabels.
func (mr *MockDefaultAPIMockRecorder) ListLabels(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLabels", reflect.TypeOf((*MockDefaultAPI)(nil).ListLabels), ctx, projectId, zoneId)
}

// ListLabelsExecute mocks base method.
func (m *MockDefaultAPI) ListLabelsExecute(r v1api.ApiListLabelsRequest) (*v1api.ListLabelsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLabelsExecute", r)
	ret0, _ := ret[0].(*v1api.ListLabelsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLabelsExecute indicates an expected call of ListLabelsExecute.
func (mr *MockDefaultAPIMockRecorder) ListLabelsExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLabelsExecute", reflect.TypeOf((*MockDefaultAPI)(nil).ListLabelsExecute), r)
}

// ListRecordSets mocks base method.
func (m *MockDefaultAPI) ListRecordSets(ctx context.Context, projectId, zoneId string) v1api.ApiListRecordSetsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecordSets", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiListRecordSetsRequest)
	return ret0
}

// ListRecordSets indicates an expected call of ListRecordSets.
func (mr *MockDefaultAPIMockRecorder) ListRecordSets(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecordSets", reflect.TypeOf((*MockDefaultAPI)(nil).ListRecordSets), ctx, projectId, zoneId)
}

// ListRecordSetsExecute mocks base method.
func (m *MockDefaultAPI) ListRecordSetsExecute(r v1api.ApiListRecordSetsRequest) (*v1api.ListRecordSetsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecordSetsExecute", r)
	ret0, _ := ret[0].(*v1api.ListRecordSetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecordSetsExecute indicates an expected call of ListRecordSetsExecute.
func (mr *MockDefaultAPIMockRecorder) ListRecordSetsExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecordSetsExecute", reflect.TypeOf((*MockDefaultAPI)(nil).ListRecordSetsExecute), r)
}

// ListZones mocks base method.
func (m *MockDefaultAPI) ListZones(ctx context.Context, projectId string) v1api.ApiListZonesRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListZones", ctx, projectId)
	ret0, _ := ret[0].(v1api.ApiListZonesRequest)
	return ret0
}

// ListZones indicates an expected call of ListZones.
func (mr *MockDefaultAPIMockRecorder) ListZones(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListZones", reflect.TypeOf((*MockDefaultAPI)(nil).ListZones), ctx, projectId)
}

// ListZonesExecute mocks base method.
func (m *MockDefaultAPI) ListZonesExecute(r v1api.ApiListZonesRequest) (*v1api.ListZonesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListZonesExecute", r)
	ret0, _ := ret[0].(*v1api.ListZonesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListZonesExecute indicates an expected call of ListZonesExecute.
func (mr *MockDefaultAPIMockRecorder) ListZonesExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListZonesExecute", reflect.TypeOf((*MockDefaultAPI)(nil).ListZonesExecute), r)
}

// MoveZone mocks base method.
func (m *MockDefaultAPI) MoveZone(ctx context.Context, projectId string) v1api.ApiMoveZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveZone", ctx, projectId)
	ret0, _ := ret[0].(v1api.ApiMoveZoneRequest)
	return ret0
}

// MoveZone indicates an expected call of MoveZone.
func (mr *MockDefaultAPIMockRecorder) MoveZone(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveZone", reflect.TypeOf((*MockDefaultAPI)(nil).MoveZone), ctx, projectId)
}

// MoveZoneExecute mocks base method.
func (m *MockDefaultAPI) MoveZoneExecute(r v1api.ApiMoveZoneRequest) (*v1api.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveZoneExecute", r)
	ret0, _ := ret[0].(*v1api.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveZoneExecute indicates an expected call of MoveZoneExecute.
func (mr *MockDefaultAPIMockRecorder) MoveZoneExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveZoneExecute", reflect.TypeOf((*MockDefaultAPI)(nil).MoveZoneExecute), r)
}

// PartialUpdateRecord mocks base method.
func (m *MockDefaultAPI) PartialUpdateRecord(ctx context.Context, projectId, zoneId, rrSetId string) v1api.ApiPartialUpdateRecordRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateRecord", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(v1api.ApiPartialUpdateRecordRequest)
	return ret0
}

// PartialUpdateRecord indicates an expected call of PartialUpdateRecord.
func (mr *MockDefaultAPIMockRecorder) PartialUpdateRecord(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateRecord", reflect.TypeOf((*MockDefaultAPI)(nil).PartialUpdateRecord), ctx, projectId, zoneId, rrSetId)
}

// PartialUpdateRecordExecute mocks base method.
func (m *MockDefaultAPI) PartialUpdateRecordExecute(r v1api.ApiPartialUpdateRecordRequest) (*v1api.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateRecordExecute", r)
	ret0, _ := ret[0].(*v1api.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PartialUpdateRecordExecute indicates an expected call of PartialUpdateRecordExecute.
func (mr *MockDefaultAPIMockRecorder) PartialUpdateRecordExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateRecordExecute", reflect.TypeOf((*MockDefaultAPI)(nil).PartialUpdateRecordExecute), r)
}

// PartialUpdateRecordSet mocks base method.
func (m *MockDefaultAPI) PartialUpdateRecordSet(ctx context.Context, projectId, zoneId, rrSetId string) v1api.ApiPartialUpdateRecordSetRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateRecordSet", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(v1api.ApiPartialUpdateRecordSetRequest)
	return ret0
}

// PartialUpdateRecordSet indicates an expected call of PartialUpdateRecordSet.
func (mr *MockDefaultAPIMockRecorder) PartialUpdateRecordSet(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateRecordSet", reflect.TypeOf((*MockDefaultAPI)(nil).PartialUpdateRecordSet), ctx, projectId, zoneId, rrSetId)
}

// PartialUpdateRecordSetExecute mocks base method.
func (m *MockDefaultAPI) PartialUpdateRecordSetExecute(r v1api.ApiPartialUpdateRecordSetRequest) (*v1api.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateRecordSetExecute", r)
	ret0, _ := ret[0].(*v1api.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PartialUpdateRecordSetExecute indicates an expected call of PartialUpdateRecordSetExecute.
func (mr *MockDefaultAPIMockRecorder) PartialUpdateRecordSetExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateRecordSetExecute", reflect.TypeOf((*MockDefaultAPI)(nil).PartialUpdateRecordSetExecute), r)
}

// PartialUpdateZone mocks base method.
func (m *MockDefaultAPI) PartialUpdateZone(ctx context.Context, projectId, zoneId string) v1api.ApiPartialUpdateZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateZone", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiPartialUpdateZoneRequest)
	return ret0
}

// PartialUpdateZone indicates an expected call of PartialUpdateZone.
func (mr *MockDefaultAPIMockRecorder) PartialUpdateZone(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateZone", reflect.TypeOf((*MockDefaultAPI)(nil).PartialUpdateZone), ctx, projectId, zoneId)
}

// PartialUpdateZoneExecute mocks base method.
func (m *MockDefaultAPI) PartialUpdateZoneExecute(r v1api.ApiPartialUpdateZoneRequest) (*v1api.ZoneResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialUpdateZoneExecute", r)
	ret0, _ := ret[0].(*v1api.ZoneResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PartialUpdateZoneExecute indicates an expected call of PartialUpdateZoneExecute.
func (mr *MockDefaultAPIMockRecorder) PartialUpdateZoneExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialUpdateZoneExecute", reflect.TypeOf((*MockDefaultAPI)(nil).PartialUpdateZoneExecute), r)
}

// RestoreRecordSet mocks base method.
func (m *MockDefaultAPI) RestoreRecordSet(ctx context.Context, projectId, zoneId, rrSetId string) v1api.ApiRestoreRecordSetRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreRecordSet", ctx, projectId, zoneId, rrSetId)
	ret0, _ := ret[0].(v1api.ApiRestoreRecordSetRequest)
	return ret0
}

// RestoreRecordSet indicates an expected call of RestoreRecordSet.
func (mr *MockDefaultAPIMockRecorder) RestoreRecordSet(ctx, projectId, zoneId, rrSetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreRecordSet", reflect.TypeOf((*MockDefaultAPI)(nil).RestoreRecordSet), ctx, projectId, zoneId, rrSetId)
}

// RestoreRecordSetExecute mocks base method.
func (m *MockDefaultAPI) RestoreRecordSetExecute(r v1api.ApiRestoreRecordSetRequest) (*v1api.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreRecordSetExecute", r)
	ret0, _ := ret[0].(*v1api.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreRecordSetExecute indicates an expected call of RestoreRecordSetExecute.
func (mr *MockDefaultAPIMockRecorder) RestoreRecordSetExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreRecordSetExecute", reflect.TypeOf((*MockDefaultAPI)(nil).RestoreRecordSetExecute), r)
}

// RestoreZone mocks base method.
func (m *MockDefaultAPI) RestoreZone(ctx context.Context, projectId, zoneId string) v1api.ApiRestoreZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreZone", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiRestoreZoneRequest)
	return ret0
}

// RestoreZone indicates an expected call of RestoreZone.
func (mr *MockDefaultAPIMockRecorder) RestoreZone(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreZone", reflect.TypeOf((*MockDefaultAPI)(nil).RestoreZone), ctx, projectId, zoneId)
}

// RestoreZoneExecute mocks base method.
func (m *MockDefaultAPI) RestoreZoneExecute(r v1api.ApiRestoreZoneRequest) (*v1api.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreZoneExecute", r)
	ret0, _ := ret[0].(*v1api.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreZoneExecute indicates an expected call of RestoreZoneExecute.
func (mr *MockDefaultAPIMockRecorder) RestoreZoneExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreZoneExecute", reflect.TypeOf((*MockDefaultAPI)(nil).RestoreZoneExecute), r)
}

// RetrieveZone mocks base method.
func (m *MockDefaultAPI) RetrieveZone(ctx context.Context, projectId, zoneId string) v1api.ApiRetrieveZoneRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveZone", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiRetrieveZoneRequest)
	return ret0
}

// RetrieveZone indicates an expected call of RetrieveZone.
func (mr *MockDefaultAPIMockRecorder) RetrieveZone(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveZone", reflect.TypeOf((*MockDefaultAPI)(nil).RetrieveZone), ctx, projectId, zoneId)
}

// RetrieveZoneExecute mocks base method.
func (m *MockDefaultAPI) RetrieveZoneExecute(r v1api.ApiRetrieveZoneRequest) (*v1api.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveZoneExecute", r)
	ret0, _ := ret[0].(*v1api.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveZoneExecute indicates an expected call of RetrieveZoneExecute.
func (mr *MockDefaultAPIMockRecorder) RetrieveZoneExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveZoneExecute", reflect.TypeOf((*MockDefaultAPI)(nil).RetrieveZoneExecute), r)
}

// ValidateMoveCode mocks base method.
func (m *MockDefaultAPI) ValidateMoveCode(ctx context.Context, projectId, zoneId string) v1api.ApiValidateMoveCodeRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateMoveCode", ctx, projectId, zoneId)
	ret0, _ := ret[0].(v1api.ApiValidateMoveCodeRequest)
	return ret0
}

// ValidateMoveCode indicates an expected call of ValidateMoveCode.
func (mr *MockDefaultAPIMockRecorder) ValidateMoveCode(ctx, projectId, zoneId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateMoveCode", reflect.TypeOf((*MockDefaultAPI)(nil).ValidateMoveCode), ctx, projectId, zoneId)
}

// ValidateMoveCodeExecute mocks base method.
func (m *MockDefaultAPI) ValidateMoveCodeExecute(r v1api.ApiValidateMoveCodeRequest) (*v1api.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateMoveCodeExecute", r)
	ret0, _ := ret[0].(*v1api.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateMoveCodeExecute indicates an expected call of ValidateMoveCodeExecute.
func (mr *MockDefaultAPIMockRecorder) ValidateMoveCodeExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateMoveCodeExecute", reflect.TypeOf((*MockDefaultAPI)(nil).ValidateMoveCodeExecute), r)
}
