---
# This is the secret you can use to activate emergency access for the LoadBalancer API.
# It needs to be deployed into the control-plane namespace of the shoot within the seed cluster.
apiVersion: v1
kind: Secret
metadata:
  name: lb-api-emergency-access
type: Opaque
stringData:
  # Should point to the API host of the LB Team (not the API Gateway).
  lbApiUrl: "https://<lb-api-endpoint>"
  # Should be set to the token which you will receive from the LB team.
  lbApiToken: "<jwt-token-from-lb-team>"
