apiVersion: v1
kind: ConfigMap
metadata:
  name: stackit-cloud-controller-manager
  namespace: {{ .Release.Namespace }}
data:
  cloud.yaml: |-
    global:
      projectId: {{ .Values.config.stackitProjectID }}
      region: {{ .Values.config.stackitRegion }}
      {{- if or .Values.config.iaasApiUrl .Values.config.loadBalancerApiUrl }}
      apiEndpoints:
        {{- if .Values.config.iaasApiUrl }}
        iaasApi: {{ .Values.config.iaasApiUrl }}
        {{- end }}
        {{- if .Values.config.loadBalancerApiUrl }}
        loadBalancerApi: {{ .Values.config.loadBalancerApiUrl }}
        {{- end }}
      {{- end }}
    loadBalancer:
      networkId: {{ .Values.config.stackitNetworkID }}
      {{- if .Values.config.extraLabels }}
      extraLabels:
        {{- toYaml .Values.config.extraLabels | nindent 8 }}
      {{- end }}
