{{ if .Values.config.caCert }}
apiVersion: v1
kind: Secret
metadata:
  name: cloud-config-extra-ca
  namespace: {{ .Release.Namespace }}
data:
  stackit-ca.crt: {{ .Values.config.caCert | b64enc }}
{{- end }}
