// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackitcloud/gardener-extension-provider-stackit/v2/pkg/stackit/client (interfaces: LoadBalancingClient)
//
// Generated by this command:
//
//	mockgen -destination ./pkg/stackit/client/mock/loadbalancing_mock.go -package client github.com/stackitcloud/gardener-extension-provider-stackit/v2/pkg/stackit/client LoadBalancingClient
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	v2api "github.com/stackitcloud/stackit-sdk-go/services/loadbalancer/v2api"
	gomock "go.uber.org/mock/gomock"
)

// MockLoadBalancingClient is a mock of LoadBalancingClient interface.
type MockLoadBalancingClient struct {
	ctrl     *gomock.Controller
	recorder *MockLoadBalancingClientMockRecorder
	isgomock struct{}
}

// MockLoadBalancingClientMockRecorder is the mock recorder for MockLoadBalancingClient.
type MockLoadBalancingClientMockRecorder struct {
	mock *MockLoadBalancingClient
}

// NewMockLoadBalancingClient creates a new mock instance.
func NewMockLoadBalancingClient(ctrl *gomock.Controller) *MockLoadBalancingClient {
	mock := &MockLoadBalancingClient{ctrl: ctrl}
	mock.recorder = &MockLoadBalancingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoadBalancingClient) EXPECT() *MockLoadBalancingClientMockRecorder {
	return m.recorder
}

// CreateLoadBalancer mocks base method.
func (m *MockLoadBalancingClient) CreateLoadBalancer(ctx context.Context, payload v2api.CreateLoadBalancerPayload) (*v2api.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoadBalancer", ctx, payload)
	ret0, _ := ret[0].(*v2api.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLoadBalancer indicates an expected call of CreateLoadBalancer.
func (mr *MockLoadBalancingClientMockRecorder) CreateLoadBalancer(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoadBalancer", reflect.TypeOf((*MockLoadBalancingClient)(nil).CreateLoadBalancer), ctx, payload)
}

// DeleteLoadBalancer mocks base method.
func (m *MockLoadBalancingClient) DeleteLoadBalancer(ctx context.Context, lbName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadBalancer", ctx, lbName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoadBalancer indicates an expected call of DeleteLoadBalancer.
func (mr *MockLoadBalancingClientMockRecorder) DeleteLoadBalancer(ctx, lbName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadBalancer", reflect.TypeOf((*MockLoadBalancingClient)(nil).DeleteLoadBalancer), ctx, lbName)
}

// GetLoadBalancer mocks base method.
func (m *MockLoadBalancingClient) GetLoadBalancer(ctx context.Context, id string) (*v2api.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadBalancer", ctx, id)
	ret0, _ := ret[0].(*v2api.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoadBalancer indicates an expected call of GetLoadBalancer.
func (mr *MockLoadBalancingClientMockRecorder) GetLoadBalancer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadBalancer", reflect.TypeOf((*MockLoadBalancingClient)(nil).GetLoadBalancer), ctx, id)
}

// ListLoadBalancers mocks base method.
func (m *MockLoadBalancingClient) ListLoadBalancers(ctx context.Context) ([]v2api.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLoadBalancers", ctx)
	ret0, _ := ret[0].([]v2api.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLoadBalancers indicates an expected call of ListLoadBalancers.
func (mr *MockLoadBalancingClientMockRecorder) ListLoadBalancers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLoadBalancers", reflect.TypeOf((*MockLoadBalancingClient)(nil).ListLoadBalancers), ctx)
}

// ProjectID mocks base method.
func (m *MockLoadBalancingClient) ProjectID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ProjectID indicates an expected call of ProjectID.
func (mr *MockLoadBalancingClientMockRecorder) ProjectID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectID", reflect.TypeOf((*MockLoadBalancingClient)(nil).ProjectID))
}

// UpdateLoadBalancer mocks base method.
func (m *MockLoadBalancingClient) UpdateLoadBalancer(ctx context.Context, lbName string, payload v2api.UpdateLoadBalancerPayload) (*v2api.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLoadBalancer", ctx, lbName, payload)
	ret0, _ := ret[0].(*v2api.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLoadBalancer indicates an expected call of UpdateLoadBalancer.
func (mr *MockLoadBalancingClientMockRecorder) UpdateLoadBalancer(ctx, lbName, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLoadBalancer", reflect.TypeOf((*MockLoadBalancingClient)(nil).UpdateLoadBalancer), ctx, lbName, payload)
}

// UpdateLoadBalancerTargetPool mocks base method.
func (m *MockLoadBalancingClient) UpdateLoadBalancerTargetPool(ctx context.Context, lbName, tpName string, payload v2api.UpdateTargetPoolPayload) (*v2api.TargetPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLoadBalancerTargetPool", ctx, lbName, tpName, payload)
	ret0, _ := ret[0].(*v2api.TargetPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLoadBalancerTargetPool indicates an expected call of UpdateLoadBalancerTargetPool.
func (mr *MockLoadBalancingClientMockRecorder) UpdateLoadBalancerTargetPool(ctx, lbName, tpName, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLoadBalancerTargetPool", reflect.TypeOf((*MockLoadBalancingClient)(nil).UpdateLoadBalancerTargetPool), ctx, lbName, tpName, payload)
}
