// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackitcloud/gardener-extension-provider-stackit/v2/pkg/stackit/client (interfaces: Factory,DNSClient)
//
// Generated by this command:
//
//	mockgen -destination ./pkg/stackit/client/mock/mocks.go -package client github.com/stackitcloud/gardener-extension-provider-stackit/v2/pkg/stackit/client Factory,DNSClient
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	client "github.com/stackitcloud/gardener-extension-provider-stackit/v2/pkg/stackit/client"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	client0 "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// DNS mocks base method.
func (m *MockFactory) DNS(arg0 context.Context, arg1 client0.Client, arg2 v1.SecretReference) (client.DNSClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DNS", arg0, arg1, arg2)
	ret0, _ := ret[0].(client.DNSClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DNS indicates an expected call of DNS.
func (mr *MockFactoryMockRecorder) DNS(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DNS", reflect.TypeOf((*MockFactory)(nil).DNS), arg0, arg1, arg2)
}

// IaaS mocks base method.
func (m *MockFactory) IaaS(arg0 context.Context, arg1 client0.Client, arg2 v1.SecretReference) (client.IaaSClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IaaS", arg0, arg1, arg2)
	ret0, _ := ret[0].(client.IaaSClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IaaS indicates an expected call of IaaS.
func (mr *MockFactoryMockRecorder) IaaS(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IaaS", reflect.TypeOf((*MockFactory)(nil).IaaS), arg0, arg1, arg2)
}

// LoadBalancing mocks base method.
func (m *MockFactory) LoadBalancing(arg0 context.Context, arg1 client0.Client, arg2 v1.SecretReference) (client.LoadBalancingClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadBalancing", arg0, arg1, arg2)
	ret0, _ := ret[0].(client.LoadBalancingClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadBalancing indicates an expected call of LoadBalancing.
func (mr *MockFactoryMockRecorder) LoadBalancing(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadBalancing", reflect.TypeOf((*MockFactory)(nil).LoadBalancing), arg0, arg1, arg2)
}

// MockDNSClient is a mock of DNSClient interface.
type MockDNSClient struct {
	ctrl     *gomock.Controller
	recorder *MockDNSClientMockRecorder
	isgomock struct{}
}

// MockDNSClientMockRecorder is the mock recorder for MockDNSClient.
type MockDNSClientMockRecorder struct {
	mock *MockDNSClient
}

// NewMockDNSClient creates a new mock instance.
func NewMockDNSClient(ctrl *gomock.Controller) *MockDNSClient {
	mock := &MockDNSClient{ctrl: ctrl}
	mock.recorder = &MockDNSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDNSClient) EXPECT() *MockDNSClientMockRecorder {
	return m.recorder
}

// CreateOrUpdateRecordSet mocks base method.
func (m *MockDNSClient) CreateOrUpdateRecordSet(ctx context.Context, zoneID, name, recordType string, records []string, ttl int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateRecordSet", ctx, zoneID, name, recordType, records, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateRecordSet indicates an expected call of CreateOrUpdateRecordSet.
func (mr *MockDNSClientMockRecorder) CreateOrUpdateRecordSet(ctx, zoneID, name, recordType, records, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateRecordSet", reflect.TypeOf((*MockDNSClient)(nil).CreateOrUpdateRecordSet), ctx, zoneID, name, recordType, records, ttl)
}

// DeleteRecordSet mocks base method.
func (m *MockDNSClient) DeleteRecordSet(ctx context.Context, zoneID, name, recordType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordSet", ctx, zoneID, name, recordType)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecordSet indicates an expected call of DeleteRecordSet.
func (mr *MockDNSClientMockRecorder) DeleteRecordSet(ctx, zoneID, name, recordType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordSet", reflect.TypeOf((*MockDNSClient)(nil).DeleteRecordSet), ctx, zoneID, name, recordType)
}

// ListZones mocks base method.
func (m *MockDNSClient) ListZones(ctx context.Context) ([]client.DNSZone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListZones", ctx)
	ret0, _ := ret[0].([]client.DNSZone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListZones indicates an expected call of ListZones.
func (mr *MockDNSClientMockRecorder) ListZones(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListZones", reflect.TypeOf((*MockDNSClient)(nil).ListZones), ctx)
}
