// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackitcloud/gardener-extension-provider-stackit/pkg/stackit/client (interfaces: Factory,IaaSClient,LoadBalancingClient,DNSClient)
//
// Generated by this command:
//
//	mockgen -package client -destination=mocks.go github.com/stackitcloud/gardener-extension-provider-stackit/pkg/stackit/client Factory,IaaSClient,LoadBalancingClient,DNSClient
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	logr "github.com/go-logr/logr"
	stackit "github.com/stackitcloud/gardener-extension-provider-stackit/v2/pkg/stackit"
	client "github.com/stackitcloud/gardener-extension-provider-stackit/v2/pkg/stackit/client"
	iaas "github.com/stackitcloud/stackit-sdk-go/services/iaas"
	loadbalancer "github.com/stackitcloud/stackit-sdk-go/services/loadbalancer"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	client0 "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// DNS mocks base method.
func (m *MockFactory) DNS(arg0 context.Context, arg1 client0.Client, arg2 v1.SecretReference) (client.DNSClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DNS", arg0, arg1, arg2)
	ret0, _ := ret[0].(client.DNSClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DNS indicates an expected call of DNS.
func (mr *MockFactoryMockRecorder) DNS(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DNS", reflect.TypeOf((*MockFactory)(nil).DNS), arg0, arg1, arg2)
}

// IaaS mocks base method.
func (m *MockFactory) IaaS(arg0 context.Context, arg1 client0.Client, arg2 v1.SecretReference) (client.IaaSClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IaaS", arg0, arg1, arg2)
	ret0, _ := ret[0].(client.IaaSClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IaaS indicates an expected call of IaaS.
func (mr *MockFactoryMockRecorder) IaaS(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IaaS", reflect.TypeOf((*MockFactory)(nil).IaaS), arg0, arg1, arg2)
}

// LoadBalancing mocks base method.
func (m *MockFactory) LoadBalancing(arg0 context.Context, arg1 client0.Client, arg2 v1.SecretReference) (client.LoadBalancingClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadBalancing", arg0, arg1, arg2)
	ret0, _ := ret[0].(client.LoadBalancingClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadBalancing indicates an expected call of LoadBalancing.
func (mr *MockFactoryMockRecorder) LoadBalancing(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadBalancing", reflect.TypeOf((*MockFactory)(nil).LoadBalancing), arg0, arg1, arg2)
}

// MockIaaSClient is a mock of IaaSClient interface.
type MockIaaSClient struct {
	ctrl     *gomock.Controller
	recorder *MockIaaSClientMockRecorder
	isgomock struct{}
}

// MockIaaSClientMockRecorder is the mock recorder for MockIaaSClient.
type MockIaaSClientMockRecorder struct {
	mock *MockIaaSClient
}

// NewMockIaaSClient creates a new mock instance.
func NewMockIaaSClient(ctrl *gomock.Controller) *MockIaaSClient {
	mock := &MockIaaSClient{ctrl: ctrl}
	mock.recorder = &MockIaaSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIaaSClient) EXPECT() *MockIaaSClientMockRecorder {
	return m.recorder
}

// AddPublicIpToServer mocks base method.
func (m *MockIaaSClient) AddPublicIpToServer(ctx context.Context, serverId, publicIpId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPublicIpToServer", ctx, serverId, publicIpId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPublicIpToServer indicates an expected call of AddPublicIpToServer.
func (mr *MockIaaSClientMockRecorder) AddPublicIpToServer(ctx, serverId, publicIpId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPublicIpToServer", reflect.TypeOf((*MockIaaSClient)(nil).AddPublicIpToServer), ctx, serverId, publicIpId)
}

// CreateIsolatedNetwork mocks base method.
func (m *MockIaaSClient) CreateIsolatedNetwork(ctx context.Context, payload iaas.CreateIsolatedNetworkPayload) (*iaas.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIsolatedNetwork", ctx, payload)
	ret0, _ := ret[0].(*iaas.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIsolatedNetwork indicates an expected call of CreateIsolatedNetwork.
func (mr *MockIaaSClientMockRecorder) CreateIsolatedNetwork(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIsolatedNetwork", reflect.TypeOf((*MockIaaSClient)(nil).CreateIsolatedNetwork), ctx, payload)
}

// CreateKeypair mocks base method.
func (m *MockIaaSClient) CreateKeypair(ctx context.Context, name, publicKey string) (*iaas.Keypair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKeypair", ctx, name, publicKey)
	ret0, _ := ret[0].(*iaas.Keypair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKeypair indicates an expected call of CreateKeypair.
func (mr *MockIaaSClientMockRecorder) CreateKeypair(ctx, name, publicKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKeypair", reflect.TypeOf((*MockIaaSClient)(nil).CreateKeypair), ctx, name, publicKey)
}

// CreatePublicIp mocks base method.
func (m *MockIaaSClient) CreatePublicIp(ctx context.Context, payload iaas.CreatePublicIPPayload) (*iaas.PublicIp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePublicIp", ctx, payload)
	ret0, _ := ret[0].(*iaas.PublicIp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePublicIp indicates an expected call of CreatePublicIp.
func (mr *MockIaaSClientMockRecorder) CreatePublicIp(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePublicIp", reflect.TypeOf((*MockIaaSClient)(nil).CreatePublicIp), ctx, payload)
}

// CreateSecurityGroup mocks base method.
func (m *MockIaaSClient) CreateSecurityGroup(ctx context.Context, payload iaas.CreateSecurityGroupPayload) (*iaas.SecurityGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecurityGroup", ctx, payload)
	ret0, _ := ret[0].(*iaas.SecurityGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecurityGroup indicates an expected call of CreateSecurityGroup.
func (mr *MockIaaSClientMockRecorder) CreateSecurityGroup(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecurityGroup", reflect.TypeOf((*MockIaaSClient)(nil).CreateSecurityGroup), ctx, payload)
}

// CreateSecurityGroupRule mocks base method.
func (m *MockIaaSClient) CreateSecurityGroupRule(ctx context.Context, securityGroupId string, wantedRule iaas.SecurityGroupRule) (*iaas.SecurityGroupRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecurityGroupRule", ctx, securityGroupId, wantedRule)
	ret0, _ := ret[0].(*iaas.SecurityGroupRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecurityGroupRule indicates an expected call of CreateSecurityGroupRule.
func (mr *MockIaaSClientMockRecorder) CreateSecurityGroupRule(ctx, securityGroupId, wantedRule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecurityGroupRule", reflect.TypeOf((*MockIaaSClient)(nil).CreateSecurityGroupRule), ctx, securityGroupId, wantedRule)
}

// CreateServer mocks base method.
func (m *MockIaaSClient) CreateServer(ctx context.Context, payload iaas.CreateServerPayload) (*iaas.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServer", ctx, payload)
	ret0, _ := ret[0].(*iaas.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServer indicates an expected call of CreateServer.
func (mr *MockIaaSClientMockRecorder) CreateServer(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServer", reflect.TypeOf((*MockIaaSClient)(nil).CreateServer), ctx, payload)
}

// DeleteKeypair mocks base method.
func (m *MockIaaSClient) DeleteKeypair(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeypair", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKeypair indicates an expected call of DeleteKeypair.
func (mr *MockIaaSClientMockRecorder) DeleteKeypair(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeypair", reflect.TypeOf((*MockIaaSClient)(nil).DeleteKeypair), ctx, name)
}

// DeleteNetwork mocks base method.
func (m *MockIaaSClient) DeleteNetwork(ctx context.Context, networkID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetwork", ctx, networkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetwork indicates an expected call of DeleteNetwork.
func (mr *MockIaaSClientMockRecorder) DeleteNetwork(ctx, networkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetwork", reflect.TypeOf((*MockIaaSClient)(nil).DeleteNetwork), ctx, networkID)
}

// DeletePublicIp mocks base method.
func (m *MockIaaSClient) DeletePublicIp(ctx context.Context, publicIpId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePublicIp", ctx, publicIpId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePublicIp indicates an expected call of DeletePublicIp.
func (mr *MockIaaSClientMockRecorder) DeletePublicIp(ctx, publicIpId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePublicIp", reflect.TypeOf((*MockIaaSClient)(nil).DeletePublicIp), ctx, publicIpId)
}

// DeleteSecurityGroup mocks base method.
func (m *MockIaaSClient) DeleteSecurityGroup(ctx context.Context, securityGroupId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecurityGroup", ctx, securityGroupId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecurityGroup indicates an expected call of DeleteSecurityGroup.
func (mr *MockIaaSClientMockRecorder) DeleteSecurityGroup(ctx, securityGroupId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecurityGroup", reflect.TypeOf((*MockIaaSClient)(nil).DeleteSecurityGroup), ctx, securityGroupId)
}

// DeleteServer mocks base method.
func (m *MockIaaSClient) DeleteServer(ctx context.Context, serverId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServer", ctx, serverId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServer indicates an expected call of DeleteServer.
func (mr *MockIaaSClientMockRecorder) DeleteServer(ctx, serverId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServer", reflect.TypeOf((*MockIaaSClient)(nil).DeleteServer), ctx, serverId)
}

// GetKeypair mocks base method.
func (m *MockIaaSClient) GetKeypair(ctx context.Context, name string) (*iaas.Keypair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeypair", ctx, name)
	ret0, _ := ret[0].(*iaas.Keypair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeypair indicates an expected call of GetKeypair.
func (mr *MockIaaSClientMockRecorder) GetKeypair(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeypair", reflect.TypeOf((*MockIaaSClient)(nil).GetKeypair), ctx, name)
}

// GetNetworkById mocks base method.
func (m *MockIaaSClient) GetNetworkById(ctx context.Context, id string) (*iaas.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkById", ctx, id)
	ret0, _ := ret[0].(*iaas.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkById indicates an expected call of GetNetworkById.
func (mr *MockIaaSClientMockRecorder) GetNetworkById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkById", reflect.TypeOf((*MockIaaSClient)(nil).GetNetworkById), ctx, id)
}

// GetNetworkByName mocks base method.
func (m *MockIaaSClient) GetNetworkByName(ctx context.Context, name string) ([]iaas.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkByName", ctx, name)
	ret0, _ := ret[0].([]iaas.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkByName indicates an expected call of GetNetworkByName.
func (mr *MockIaaSClientMockRecorder) GetNetworkByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkByName", reflect.TypeOf((*MockIaaSClient)(nil).GetNetworkByName), ctx, name)
}

// GetPublicIpByLabels mocks base method.
func (m *MockIaaSClient) GetPublicIpByLabels(ctx context.Context, selector stackit.LabelSelector) ([]iaas.PublicIp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicIpByLabels", ctx, selector)
	ret0, _ := ret[0].([]iaas.PublicIp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicIpByLabels indicates an expected call of GetPublicIpByLabels.
func (mr *MockIaaSClientMockRecorder) GetPublicIpByLabels(ctx, selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicIpByLabels", reflect.TypeOf((*MockIaaSClient)(nil).GetPublicIpByLabels), ctx, selector)
}

// GetSecurityGroupById mocks base method.
func (m *MockIaaSClient) GetSecurityGroupById(ctx context.Context, securityGroupId string) (*iaas.SecurityGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityGroupById", ctx, securityGroupId)
	ret0, _ := ret[0].(*iaas.SecurityGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityGroupById indicates an expected call of GetSecurityGroupById.
func (mr *MockIaaSClientMockRecorder) GetSecurityGroupById(ctx, securityGroupId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityGroupById", reflect.TypeOf((*MockIaaSClient)(nil).GetSecurityGroupById), ctx, securityGroupId)
}

// GetSecurityGroupByName mocks base method.
func (m *MockIaaSClient) GetSecurityGroupByName(ctx context.Context, name string) ([]iaas.SecurityGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityGroupByName", ctx, name)
	ret0, _ := ret[0].([]iaas.SecurityGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityGroupByName indicates an expected call of GetSecurityGroupByName.
func (mr *MockIaaSClientMockRecorder) GetSecurityGroupByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityGroupByName", reflect.TypeOf((*MockIaaSClient)(nil).GetSecurityGroupByName), ctx, name)
}

// GetServerByName mocks base method.
func (m *MockIaaSClient) GetServerByName(ctx context.Context, name string) ([]iaas.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerByName", ctx, name)
	ret0, _ := ret[0].([]iaas.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerByName indicates an expected call of GetServerByName.
func (mr *MockIaaSClientMockRecorder) GetServerByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerByName", reflect.TypeOf((*MockIaaSClient)(nil).GetServerByName), ctx, name)
}

// ProjectID mocks base method.
func (m *MockIaaSClient) ProjectID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ProjectID indicates an expected call of ProjectID.
func (mr *MockIaaSClientMockRecorder) ProjectID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectID", reflect.TypeOf((*MockIaaSClient)(nil).ProjectID))
}

// ReconcileSecurityGroupRules mocks base method.
func (m *MockIaaSClient) ReconcileSecurityGroupRules(ctx context.Context, log logr.Logger, securityGroup *iaas.SecurityGroup, wantedRules []iaas.SecurityGroupRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileSecurityGroupRules", ctx, log, securityGroup, wantedRules)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileSecurityGroupRules indicates an expected call of ReconcileSecurityGroupRules.
func (mr *MockIaaSClientMockRecorder) ReconcileSecurityGroupRules(ctx, log, securityGroup, wantedRules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileSecurityGroupRules", reflect.TypeOf((*MockIaaSClient)(nil).ReconcileSecurityGroupRules), ctx, log, securityGroup, wantedRules)
}

// UpdateNetwork mocks base method.
func (m *MockIaaSClient) UpdateNetwork(ctx context.Context, networkId string, payload iaas.PartialUpdateNetworkPayload) (*iaas.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNetwork", ctx, networkId, payload)
	ret0, _ := ret[0].(*iaas.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNetwork indicates an expected call of UpdateNetwork.
func (mr *MockIaaSClientMockRecorder) UpdateNetwork(ctx, networkId, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNetwork", reflect.TypeOf((*MockIaaSClient)(nil).UpdateNetwork), ctx, networkId, payload)
}

// UpdateSecurityGroupRules mocks base method.
func (m *MockIaaSClient) UpdateSecurityGroupRules(ctx context.Context, group *iaas.SecurityGroup, desiredRules []iaas.SecurityGroupRule, allowDelete func(*iaas.SecurityGroupRule) bool) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecurityGroupRules", ctx, group, desiredRules, allowDelete)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSecurityGroupRules indicates an expected call of UpdateSecurityGroupRules.
func (mr *MockIaaSClientMockRecorder) UpdateSecurityGroupRules(ctx, group, desiredRules, allowDelete any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecurityGroupRules", reflect.TypeOf((*MockIaaSClient)(nil).UpdateSecurityGroupRules), ctx, group, desiredRules, allowDelete)
}

// MockLoadBalancingClient is a mock of LoadBalancingClient interface.
type MockLoadBalancingClient struct {
	ctrl     *gomock.Controller
	recorder *MockLoadBalancingClientMockRecorder
	isgomock struct{}
}

// MockLoadBalancingClientMockRecorder is the mock recorder for MockLoadBalancingClient.
type MockLoadBalancingClientMockRecorder struct {
	mock *MockLoadBalancingClient
}

// NewMockLoadBalancingClient creates a new mock instance.
func NewMockLoadBalancingClient(ctrl *gomock.Controller) *MockLoadBalancingClient {
	mock := &MockLoadBalancingClient{ctrl: ctrl}
	mock.recorder = &MockLoadBalancingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoadBalancingClient) EXPECT() *MockLoadBalancingClientMockRecorder {
	return m.recorder
}

// DeleteLoadBalancer mocks base method.
func (m *MockLoadBalancingClient) DeleteLoadBalancer(ctx context.Context, lbName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadBalancer", ctx, lbName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoadBalancer indicates an expected call of DeleteLoadBalancer.
func (mr *MockLoadBalancingClientMockRecorder) DeleteLoadBalancer(ctx, lbName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadBalancer", reflect.TypeOf((*MockLoadBalancingClient)(nil).DeleteLoadBalancer), ctx, lbName)
}

// GetLoadBalancer mocks base method.
func (m *MockLoadBalancingClient) GetLoadBalancer(ctx context.Context, id string) (*loadbalancer.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadBalancer", ctx, id)
	ret0, _ := ret[0].(*loadbalancer.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoadBalancer indicates an expected call of GetLoadBalancer.
func (mr *MockLoadBalancingClientMockRecorder) GetLoadBalancer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadBalancer", reflect.TypeOf((*MockLoadBalancingClient)(nil).GetLoadBalancer), ctx, id)
}

// ListLoadBalancers mocks base method.
func (m *MockLoadBalancingClient) ListLoadBalancers(ctx context.Context) ([]loadbalancer.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLoadBalancers", ctx)
	ret0, _ := ret[0].([]loadbalancer.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLoadBalancers indicates an expected call of ListLoadBalancers.
func (mr *MockLoadBalancingClientMockRecorder) ListLoadBalancers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLoadBalancers", reflect.TypeOf((*MockLoadBalancingClient)(nil).ListLoadBalancers), ctx)
}

// MockDNSClient is a mock of DNSClient interface.
type MockDNSClient struct {
	ctrl     *gomock.Controller
	recorder *MockDNSClientMockRecorder
	isgomock struct{}
}

// MockDNSClientMockRecorder is the mock recorder for MockDNSClient.
type MockDNSClientMockRecorder struct {
	mock *MockDNSClient
}

// NewMockDNSClient creates a new mock instance.
func NewMockDNSClient(ctrl *gomock.Controller) *MockDNSClient {
	mock := &MockDNSClient{ctrl: ctrl}
	mock.recorder = &MockDNSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDNSClient) EXPECT() *MockDNSClientMockRecorder {
	return m.recorder
}

// CreateOrUpdateRecordSet mocks base method.
func (m *MockDNSClient) CreateOrUpdateRecordSet(ctx context.Context, zoneID, name, recordType string, records []string, ttl int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateRecordSet", ctx, zoneID, name, recordType, records, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateRecordSet indicates an expected call of CreateOrUpdateRecordSet.
func (mr *MockDNSClientMockRecorder) CreateOrUpdateRecordSet(ctx, zoneID, name, recordType, records, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateRecordSet", reflect.TypeOf((*MockDNSClient)(nil).CreateOrUpdateRecordSet), ctx, zoneID, name, recordType, records, ttl)
}

// DeleteRecordSet mocks base method.
func (m *MockDNSClient) DeleteRecordSet(ctx context.Context, zoneID, name, recordType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordSet", ctx, zoneID, name, recordType)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecordSet indicates an expected call of DeleteRecordSet.
func (mr *MockDNSClientMockRecorder) DeleteRecordSet(ctx, zoneID, name, recordType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordSet", reflect.TypeOf((*MockDNSClient)(nil).DeleteRecordSet), ctx, zoneID, name, recordType)
}

// ListZones mocks base method.
func (m *MockDNSClient) ListZones(ctx context.Context) ([]client.DNSZone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListZones", ctx)
	ret0, _ := ret[0].([]client.DNSZone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListZones indicates an expected call of ListZones.
func (mr *MockDNSClientMockRecorder) ListZones(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListZones", reflect.TypeOf((*MockDNSClient)(nil).ListZones), ctx)
}
