version: "2"

run:
  issues-exit-code: 1
  tests: true

linters:
  default: none
  enable:
    - copyloopvar
    - ginkgolinter
    - gocritic
    - gosec
    - importas
    - misspell
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    importas:
      alias:
        # internal packages
        - pkg: github.com/stackitcloud/gardener-extension-provider-stackit/v2/pkg/apis/stackit/v1alpha1
          alias: stackitv1alpha1
        # External imported packages
        - pkg: k8s.io/api/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: k8s.io/apimachinery/pkg/apis/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: k8s.io/apimachinery/pkg/api/([^m]\w+)
          alias: api${1}
        - pkg: k8s.io/apimachinery/pkg/util/(\w+)
          alias: util${1}
        - pkg: k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1
          alias: vpaautoscalingv1
        - pkg: sigs.k8s.io/controller-runtime/pkg/client/fake
          alias: fakeclient
        - pkg: sigs.k8s.io/controller-runtime/pkg/log/zap
          alias: logzap
        - pkg: sigs.k8s.io/controller-runtime/pkg/log
          alias: logf
        - pkg: go.uber.org/mock/gomock
          alias: gmock
        # gardener/gardener packages
        - pkg: github.com/gardener/gardener/pkg/component/(\w+)/constants
          alias: ${1}constants
        - pkg: github.com/gardener/gardener/extensions/pkg/webhook
          alias: extensionswebhook
        - pkg: github.com/gardener/gardener/extensions/pkg/util/secret/manager
          alias: extensionssecretmanager
        - pkg: github.com/gardener/gardener/pkg/utils/gardener
          alias: gutil
        - pkg: github.com/gardener/gardener/pkg/utils/kubernetes
          alias: kutil
        - pkg: github.com/gardener/etcd-druid/api/core/v1alpha1
          alias: druidcorev1alpha1
        - pkg: github.com/gardener/etcd-druid/api/core/crds
          alias: druidcorecrds
    misspell:
      locale: US
    nolintlint:
      require-specific: true
    revive:
      rules:
        - name: context-as-argument
        - name: duplicated-imports
        - name: early-return
        - name: exported
        - name: unreachable-code
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
        - staticcheck
        text: 'SA1019:' # Excludes messages where deprecated variables are used
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - revive
        path: _test\.go
        text: dot-imports
      - linters: # ignore long lines in copyright
          - lll
        source: "^// Copyright"
      - linters:
          - nolintlint
        text: "should be written without leading space as `//nolint" # don't require machine-readable nolint directives (i.e. with no leading space)
    paths:
      - zz_generated\..*\.go$

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
  exclusions:
    generated: lax
