replicas: 1
config:
  global:
    region: ""
    projectId: ""
    # apiEndpoints:
    #  applicationLoadBalancerApi: "foo"
    #  applicationLoadBalancerCertificateApi: "foo"
  applicationLoadBalancer:
    networkId: ""
#tokenEndpoint: "foo"
metricsPort: 9090
podAnnotations: {}
podLabels: {}
images:
  stackit-application-load-balancer-controller: image:tag
vpa:
  resourcePolicy:
    maxAllowed:
      cpu: 1
      memory: 512Mi
