global:
  genericTokenKubeconfigSecretName: generic-token-kubeconfig
cloud-controller-manager:
  enabled: true
stackit-cloud-controller-manager:
  enabled: false
csi-driver-controller:
  enabled: true
stackit-application-load-balancer-controller:
  enabled: false
stackit-pod-identity-webhook:
  enabled: false
