apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: stackit-pod-identity-webhook
  labels:
    app.kubernetes.io/name: stackit-pod-identity-webhook
webhooks:
  - name: stackit-pod-identity-webhook.stackit.cloud
    clientConfig:
      service:
        name: stackit-pod-identity-webhook
        namespace: {{ .Release.Namespace }}
        path: "/mutate--v1-pod"
        caBundle: {{ .Values.webhook.caBundle | b64enc }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system", "garden"]
        - key: gardener.cloud/role
          operator: DoesNotExist
        - key: workload-identity.stackit.cloud/skip-pod-identity-webhook
          operator: DoesNotExist
    objectSelector:
      matchExpressions:
        - key: workload-identity.stackit.cloud/skip-pod-identity-webhook
          operator: DoesNotExist
