{{ if .Values.stackitEndpoints.caCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prefix}}-stackit-ca
  namespace: {{ .Release.Namespace }}
data:
  stackit-ca.crt: {{ .Values.stackitEndpoints.caCert | b64enc }}
{{- end }}
