apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.prefix }}-csi
    role: controller
  name: {{ .Values.prefix }}-csi-driver-controller
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app: {{ .Values.prefix }}-csi
    role: controller
  type: ClusterIP
