apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackit-application-load-balancer-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: stackit-application-load-balancer-controller
    high-availability-config.resources.gardener.cloud/type: controller
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kubernetes
      role: stackit-application-load-balancer-controller
  template:
    metadata:
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        gardener.cloud/role: controlplane
        app: kubernetes
        role: stackit-application-load-balancer-controller
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-private-networks: allowed
        networking.resources.gardener.cloud/to-kube-apiserver-tcp-443: allowed
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
      terminationGracePeriodSeconds: 30
      automountServiceAccountToken: false
      priorityClassName: gardener-system-300
      containers:
      - name: stackit-application-load-balancer-controller
        image: {{ index .Values.images "stackit-application-load-balancer-controller" }}
        args:
        - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
        - --leader-elect=true
        - --metrics-bind-address=:{{ .Values.metricsPort }}
        - --leader-election-namespace=kube-system
        - --leader-election-id=stackit-application-load-balancer-controller
        - --cloud-config=/etc/config/cloud.yaml
        env:
        - name: STACKIT_SERVICE_ACCOUNT_KEY_PATH
          value: /etc/serviceaccount/serviceaccount.json
{{- if .Values.tokenEndpoint }}
        - name: STACKIT_TOKEN_BASEURL
          value: {{ .Values.tokenEndpoint }}
{{- end }}
        ports:
        - containerPort: {{ .Values.metricsPort }}
          name: metrics
          protocol: TCP
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
        volumeMounts:
        - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/config
          name: config-volume
        - mountPath: /etc/serviceaccount
          name: sa-secret
        - mountPath: /etc/ssl/certs/keystone-ca.crt
          name: cloud-config-ca
          subPath: keystone-ca.crt
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          name: stackit-application-load-balancer-controller
      - name: sa-secret
        secret:
          defaultMode: 420
          secretName: cloudprovider
          items:
            - key: "serviceaccount.json"
              path: "serviceaccount.json"
      - name: cloud-config-ca
        secret:
          secretName: cloud-provider-config
          optional: true
      - name: kubeconfig
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
                - key: kubeconfig
                  path: kubeconfig
              name: {{ .Values.global.genericTokenKubeconfigSecretName }}
              optional: false
          - secret:
              items:
                - key: token
                  path: token
              name: shoot-access-cloud-controller-manager
              optional: false
