{{- if .Values.cloudProfileCABundle }}
apiVersion: v1
kind: Secret
metadata:
  name: stackit-ca-bundle
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.cloudProfileCABundleB64 }}
  stackit-ca.crt: {{ .Values.cloudProfileCABundleB64 }}
  {{- end }}
{{- end }}
