// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate-imagename-constants.sh. DO NOT EDIT.

package imagevector

const (
	// ImageNameCloudControllerManager is a constant for an image in the image vector with name 'cloud-controller-manager'.
	ImageNameCloudControllerManager = "cloud-controller-manager"
	// ImageNameCsiAttacher is a constant for an image in the image vector with name 'csi-attacher'.
	ImageNameCsiAttacher = "csi-attacher"
	// ImageNameCsiDriverCinder is a constant for an image in the image vector with name 'csi-driver-cinder'.
	ImageNameCsiDriverCinder = "csi-driver-cinder"
	// ImageNameCsiDriverStackit is a constant for an image in the image vector with name 'csi-driver-stackit'.
	ImageNameCsiDriverStackit = "csi-driver-stackit"
	// ImageNameCsiLivenessProbe is a constant for an image in the image vector with name 'csi-liveness-probe'.
	ImageNameCsiLivenessProbe = "csi-liveness-probe"
	// ImageNameCsiNodeDriverRegistrar is a constant for an image in the image vector with name 'csi-node-driver-registrar'.
	ImageNameCsiNodeDriverRegistrar = "csi-node-driver-registrar"
	// ImageNameCsiProvisioner is a constant for an image in the image vector with name 'csi-provisioner'.
	ImageNameCsiProvisioner = "csi-provisioner"
	// ImageNameCsiResizer is a constant for an image in the image vector with name 'csi-resizer'.
	ImageNameCsiResizer = "csi-resizer"
	// ImageNameCsiSnapshotController is a constant for an image in the image vector with name 'csi-snapshot-controller'.
	ImageNameCsiSnapshotController = "csi-snapshot-controller"
	// ImageNameCsiSnapshotter is a constant for an image in the image vector with name 'csi-snapshotter'.
	ImageNameCsiSnapshotter = "csi-snapshotter"
	// ImageNameMachineControllerManagerProviderOpenstack is a constant for an image in the image vector with name 'machine-controller-manager-provider-openstack'.
	ImageNameMachineControllerManagerProviderOpenstack = "machine-controller-manager-provider-openstack"
	// ImageNameMachineControllerManagerProviderStackit is a constant for an image in the image vector with name 'machine-controller-manager-provider-stackit'.
	ImageNameMachineControllerManagerProviderStackit = "machine-controller-manager-provider-stackit"
	// ImageNameStackitAlbControllerManager is a constant for an image in the image vector with name 'stackit-alb-controller-manager'.
	ImageNameStackitAlbControllerManager = "stackit-alb-controller-manager"
	// ImageNameStackitCloudControllerManager is a constant for an image in the image vector with name 'stackit-cloud-controller-manager'.
	ImageNameStackitCloudControllerManager = "stackit-cloud-controller-manager"
)
