// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackitcloud/stackit-sdk-go/services/loadbalancer/v2api (interfaces: DefaultAPI)
//
// Generated by this command:
//
//	mockgen -destination ./pkg/stackit/client/mock/loadbalancer/loadbalancer.go -package loadbalancer -imports loadbalancerv2api=github.com/stackitcloud/stackit-sdk-go/services/loadbalancer/v2api github.com/stackitcloud/stackit-sdk-go/services/loadbalancer/v2api DefaultAPI
//

// Package loadbalancer is a generated GoMock package.
package loadbalancer

import (
	context "context"
	reflect "reflect"

	loadbalancerv2api "github.com/stackitcloud/stackit-sdk-go/services/loadbalancer/v2api"
	gomock "go.uber.org/mock/gomock"
)

// MockDefaultAPI is a mock of DefaultAPI interface.
type MockDefaultAPI struct {
	ctrl     *gomock.Controller
	recorder *MockDefaultAPIMockRecorder
	isgomock struct{}
}

// MockDefaultAPIMockRecorder is the mock recorder for MockDefaultAPI.
type MockDefaultAPIMockRecorder struct {
	mock *MockDefaultAPI
}

// NewMockDefaultAPI creates a new mock instance.
func NewMockDefaultAPI(ctrl *gomock.Controller) *MockDefaultAPI {
	mock := &MockDefaultAPI{ctrl: ctrl}
	mock.recorder = &MockDefaultAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDefaultAPI) EXPECT() *MockDefaultAPIMockRecorder {
	return m.recorder
}

// CreateCredentials mocks base method.
func (m *MockDefaultAPI) CreateCredentials(ctx context.Context, projectId, region string) loadbalancerv2api.ApiCreateCredentialsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredentials", ctx, projectId, region)
	ret0, _ := ret[0].(loadbalancerv2api.ApiCreateCredentialsRequest)
	return ret0
}

// CreateCredentials indicates an expected call of CreateCredentials.
func (mr *MockDefaultAPIMockRecorder) CreateCredentials(ctx, projectId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredentials", reflect.TypeOf((*MockDefaultAPI)(nil).CreateCredentials), ctx, projectId, region)
}

// CreateCredentialsExecute mocks base method.
func (m *MockDefaultAPI) CreateCredentialsExecute(r loadbalancerv2api.ApiCreateCredentialsRequest) (*loadbalancerv2api.CreateCredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredentialsExecute", r)
	ret0, _ := ret[0].(*loadbalancerv2api.CreateCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCredentialsExecute indicates an expected call of CreateCredentialsExecute.
func (mr *MockDefaultAPIMockRecorder) CreateCredentialsExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredentialsExecute", reflect.TypeOf((*MockDefaultAPI)(nil).CreateCredentialsExecute), r)
}

// CreateLoadBalancer mocks base method.
func (m *MockDefaultAPI) CreateLoadBalancer(ctx context.Context, projectId, region string) loadbalancerv2api.ApiCreateLoadBalancerRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoadBalancer", ctx, projectId, region)
	ret0, _ := ret[0].(loadbalancerv2api.ApiCreateLoadBalancerRequest)
	return ret0
}

// CreateLoadBalancer indicates an expected call of CreateLoadBalancer.
func (mr *MockDefaultAPIMockRecorder) CreateLoadBalancer(ctx, projectId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoadBalancer", reflect.TypeOf((*MockDefaultAPI)(nil).CreateLoadBalancer), ctx, projectId, region)
}

// CreateLoadBalancerExecute mocks base method.
func (m *MockDefaultAPI) CreateLoadBalancerExecute(r loadbalancerv2api.ApiCreateLoadBalancerRequest) (*loadbalancerv2api.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoadBalancerExecute", r)
	ret0, _ := ret[0].(*loadbalancerv2api.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLoadBalancerExecute indicates an expected call of CreateLoadBalancerExecute.
func (mr *MockDefaultAPIMockRecorder) CreateLoadBalancerExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoadBalancerExecute", reflect.TypeOf((*MockDefaultAPI)(nil).CreateLoadBalancerExecute), r)
}

// DeleteCredentials mocks base method.
func (m *MockDefaultAPI) DeleteCredentials(ctx context.Context, projectId, region, credentialsRef string) loadbalancerv2api.ApiDeleteCredentialsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredentials", ctx, projectId, region, credentialsRef)
	ret0, _ := ret[0].(loadbalancerv2api.ApiDeleteCredentialsRequest)
	return ret0
}

// DeleteCredentials indicates an expected call of DeleteCredentials.
func (mr *MockDefaultAPIMockRecorder) DeleteCredentials(ctx, projectId, region, credentialsRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredentials", reflect.TypeOf((*MockDefaultAPI)(nil).DeleteCredentials), ctx, projectId, region, credentialsRef)
}

// DeleteCredentialsExecute mocks base method.
func (m *MockDefaultAPI) DeleteCredentialsExecute(r loadbalancerv2api.ApiDeleteCredentialsRequest) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredentialsExecute", r)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCredentialsExecute indicates an expected call of DeleteCredentialsExecute.
func (mr *MockDefaultAPIMockRecorder) DeleteCredentialsExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredentialsExecute", reflect.TypeOf((*MockDefaultAPI)(nil).DeleteCredentialsExecute), r)
}

// DeleteLoadBalancer mocks base method.
func (m *MockDefaultAPI) DeleteLoadBalancer(ctx context.Context, projectId, region, name string) loadbalancerv2api.ApiDeleteLoadBalancerRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadBalancer", ctx, projectId, region, name)
	ret0, _ := ret[0].(loadbalancerv2api.ApiDeleteLoadBalancerRequest)
	return ret0
}

// DeleteLoadBalancer indicates an expected call of DeleteLoadBalancer.
func (mr *MockDefaultAPIMockRecorder) DeleteLoadBalancer(ctx, projectId, region, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadBalancer", reflect.TypeOf((*MockDefaultAPI)(nil).DeleteLoadBalancer), ctx, projectId, region, name)
}

// DeleteLoadBalancerExecute mocks base method.
func (m *MockDefaultAPI) DeleteLoadBalancerExecute(r loadbalancerv2api.ApiDeleteLoadBalancerRequest) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadBalancerExecute", r)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLoadBalancerExecute indicates an expected call of DeleteLoadBalancerExecute.
func (mr *MockDefaultAPIMockRecorder) DeleteLoadBalancerExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadBalancerExecute", reflect.TypeOf((*MockDefaultAPI)(nil).DeleteLoadBalancerExecute), r)
}

// GetCredentials mocks base method.
func (m *MockDefaultAPI) GetCredentials(ctx context.Context, projectId, region, credentialsRef string) loadbalancerv2api.ApiGetCredentialsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentials", ctx, projectId, region, credentialsRef)
	ret0, _ := ret[0].(loadbalancerv2api.ApiGetCredentialsRequest)
	return ret0
}

// GetCredentials indicates an expected call of GetCredentials.
func (mr *MockDefaultAPIMockRecorder) GetCredentials(ctx, projectId, region, credentialsRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentials", reflect.TypeOf((*MockDefaultAPI)(nil).GetCredentials), ctx, projectId, region, credentialsRef)
}

// GetCredentialsExecute mocks base method.
func (m *MockDefaultAPI) GetCredentialsExecute(r loadbalancerv2api.ApiGetCredentialsRequest) (*loadbalancerv2api.GetCredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialsExecute", r)
	ret0, _ := ret[0].(*loadbalancerv2api.GetCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialsExecute indicates an expected call of GetCredentialsExecute.
func (mr *MockDefaultAPIMockRecorder) GetCredentialsExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialsExecute", reflect.TypeOf((*MockDefaultAPI)(nil).GetCredentialsExecute), r)
}

// GetLoadBalancer mocks base method.
func (m *MockDefaultAPI) GetLoadBalancer(ctx context.Context, projectId, region, name string) loadbalancerv2api.ApiGetLoadBalancerRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadBalancer", ctx, projectId, region, name)
	ret0, _ := ret[0].(loadbalancerv2api.ApiGetLoadBalancerRequest)
	return ret0
}

// GetLoadBalancer indicates an expected call of GetLoadBalancer.
func (mr *MockDefaultAPIMockRecorder) GetLoadBalancer(ctx, projectId, region, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadBalancer", reflect.TypeOf((*MockDefaultAPI)(nil).GetLoadBalancer), ctx, projectId, region, name)
}

// GetLoadBalancerExecute mocks base method.
func (m *MockDefaultAPI) GetLoadBalancerExecute(r loadbalancerv2api.ApiGetLoadBalancerRequest) (*loadbalancerv2api.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadBalancerExecute", r)
	ret0, _ := ret[0].(*loadbalancerv2api.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoadBalancerExecute indicates an expected call of GetLoadBalancerExecute.
func (mr *MockDefaultAPIMockRecorder) GetLoadBalancerExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadBalancerExecute", reflect.TypeOf((*MockDefaultAPI)(nil).GetLoadBalancerExecute), r)
}

// GetQuota mocks base method.
func (m *MockDefaultAPI) GetQuota(ctx context.Context, projectId, region string) loadbalancerv2api.ApiGetQuotaRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuota", ctx, projectId, region)
	ret0, _ := ret[0].(loadbalancerv2api.ApiGetQuotaRequest)
	return ret0
}

// GetQuota indicates an expected call of GetQuota.
func (mr *MockDefaultAPIMockRecorder) GetQuota(ctx, projectId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuota", reflect.TypeOf((*MockDefaultAPI)(nil).GetQuota), ctx, projectId, region)
}

// GetQuotaExecute mocks base method.
func (m *MockDefaultAPI) GetQuotaExecute(r loadbalancerv2api.ApiGetQuotaRequest) (*loadbalancerv2api.GetQuotaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotaExecute", r)
	ret0, _ := ret[0].(*loadbalancerv2api.GetQuotaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotaExecute indicates an expected call of GetQuotaExecute.
func (mr *MockDefaultAPIMockRecorder) GetQuotaExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotaExecute", reflect.TypeOf((*MockDefaultAPI)(nil).GetQuotaExecute), r)
}

// ListCredentials mocks base method.
func (m *MockDefaultAPI) ListCredentials(ctx context.Context, projectId, region string) loadbalancerv2api.ApiListCredentialsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCredentials", ctx, projectId, region)
	ret0, _ := ret[0].(loadbalancerv2api.ApiListCredentialsRequest)
	return ret0
}

// ListCredentials indicates an expected call of ListCredentials.
func (mr *MockDefaultAPIMockRecorder) ListCredentials(ctx, projectId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCredentials", reflect.TypeOf((*MockDefaultAPI)(nil).ListCredentials), ctx, projectId, region)
}

// ListCredentialsExecute mocks base method.
func (m *MockDefaultAPI) ListCredentialsExecute(r loadbalancerv2api.ApiListCredentialsRequest) (*loadbalancerv2api.ListCredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCredentialsExecute", r)
	ret0, _ := ret[0].(*loadbalancerv2api.ListCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCredentialsExecute indicates an expected call of ListCredentialsExecute.
func (mr *MockDefaultAPIMockRecorder) ListCredentialsExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCredentialsExecute", reflect.TypeOf((*MockDefaultAPI)(nil).ListCredentialsExecute), r)
}

// ListLoadBalancers mocks base method.
func (m *MockDefaultAPI) ListLoadBalancers(ctx context.Context, projectId, region string) loadbalancerv2api.ApiListLoadBalancersRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLoadBalancers", ctx, projectId, region)
	ret0, _ := ret[0].(loadbalancerv2api.ApiListLoadBalancersRequest)
	return ret0
}

// ListLoadBalancers indicates an expected call of ListLoadBalancers.
func (mr *MockDefaultAPIMockRecorder) ListLoadBalancers(ctx, projectId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLoadBalancers", reflect.TypeOf((*MockDefaultAPI)(nil).ListLoadBalancers), ctx, projectId, region)
}

// ListLoadBalancersExecute mocks base method.
func (m *MockDefaultAPI) ListLoadBalancersExecute(r loadbalancerv2api.ApiListLoadBalancersRequest) (*loadbalancerv2api.ListLoadBalancersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLoadBalancersExecute", r)
	ret0, _ := ret[0].(*loadbalancerv2api.ListLoadBalancersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLoadBalancersExecute indicates an expected call of ListLoadBalancersExecute.
func (mr *MockDefaultAPIMockRecorder) ListLoadBalancersExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLoadBalancersExecute", reflect.TypeOf((*MockDefaultAPI)(nil).ListLoadBalancersExecute), r)
}

// ListPlans mocks base method.
func (m *MockDefaultAPI) ListPlans(ctx context.Context, region string) loadbalancerv2api.ApiListPlansRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlans", ctx, region)
	ret0, _ := ret[0].(loadbalancerv2api.ApiListPlansRequest)
	return ret0
}

// ListPlans indicates an expected call of ListPlans.
func (mr *MockDefaultAPIMockRecorder) ListPlans(ctx, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlans", reflect.TypeOf((*MockDefaultAPI)(nil).ListPlans), ctx, region)
}

// ListPlansExecute mocks base method.
func (m *MockDefaultAPI) ListPlansExecute(r loadbalancerv2api.ApiListPlansRequest) (*loadbalancerv2api.ListPlansResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlansExecute", r)
	ret0, _ := ret[0].(*loadbalancerv2api.ListPlansResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPlansExecute indicates an expected call of ListPlansExecute.
func (mr *MockDefaultAPIMockRecorder) ListPlansExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlansExecute", reflect.TypeOf((*MockDefaultAPI)(nil).ListPlansExecute), r)
}

// UpdateCredentials mocks base method.
func (m *MockDefaultAPI) UpdateCredentials(ctx context.Context, projectId, region, credentialsRef string) loadbalancerv2api.ApiUpdateCredentialsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredentials", ctx, projectId, region, credentialsRef)
	ret0, _ := ret[0].(loadbalancerv2api.ApiUpdateCredentialsRequest)
	return ret0
}

// UpdateCredentials indicates an expected call of UpdateCredentials.
func (mr *MockDefaultAPIMockRecorder) UpdateCredentials(ctx, projectId, region, credentialsRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredentials", reflect.TypeOf((*MockDefaultAPI)(nil).UpdateCredentials), ctx, projectId, region, credentialsRef)
}

// UpdateCredentialsExecute mocks base method.
func (m *MockDefaultAPI) UpdateCredentialsExecute(r loadbalancerv2api.ApiUpdateCredentialsRequest) (*loadbalancerv2api.UpdateCredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredentialsExecute", r)
	ret0, _ := ret[0].(*loadbalancerv2api.UpdateCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCredentialsExecute indicates an expected call of UpdateCredentialsExecute.
func (mr *MockDefaultAPIMockRecorder) UpdateCredentialsExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredentialsExecute", reflect.TypeOf((*MockDefaultAPI)(nil).UpdateCredentialsExecute), r)
}

// UpdateLoadBalancer mocks base method.
func (m *MockDefaultAPI) UpdateLoadBalancer(ctx context.Context, projectId, region, name string) loadbalancerv2api.ApiUpdateLoadBalancerRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLoadBalancer", ctx, projectId, region, name)
	ret0, _ := ret[0].(loadbalancerv2api.ApiUpdateLoadBalancerRequest)
	return ret0
}

// UpdateLoadBalancer indicates an expected call of UpdateLoadBalancer.
func (mr *MockDefaultAPIMockRecorder) UpdateLoadBalancer(ctx, projectId, region, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLoadBalancer", reflect.TypeOf((*MockDefaultAPI)(nil).UpdateLoadBalancer), ctx, projectId, region, name)
}

// UpdateLoadBalancerExecute mocks base method.
func (m *MockDefaultAPI) UpdateLoadBalancerExecute(r loadbalancerv2api.ApiUpdateLoadBalancerRequest) (*loadbalancerv2api.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLoadBalancerExecute", r)
	ret0, _ := ret[0].(*loadbalancerv2api.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLoadBalancerExecute indicates an expected call of UpdateLoadBalancerExecute.
func (mr *MockDefaultAPIMockRecorder) UpdateLoadBalancerExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLoadBalancerExecute", reflect.TypeOf((*MockDefaultAPI)(nil).UpdateLoadBalancerExecute), r)
}

// UpdateTargetPool mocks base method.
func (m *MockDefaultAPI) UpdateTargetPool(ctx context.Context, projectId, region, name, targetPoolName string) loadbalancerv2api.ApiUpdateTargetPoolRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTargetPool", ctx, projectId, region, name, targetPoolName)
	ret0, _ := ret[0].(loadbalancerv2api.ApiUpdateTargetPoolRequest)
	return ret0
}

// UpdateTargetPool indicates an expected call of UpdateTargetPool.
func (mr *MockDefaultAPIMockRecorder) UpdateTargetPool(ctx, projectId, region, name, targetPoolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTargetPool", reflect.TypeOf((*MockDefaultAPI)(nil).UpdateTargetPool), ctx, projectId, region, name, targetPoolName)
}

// UpdateTargetPoolExecute mocks base method.
func (m *MockDefaultAPI) UpdateTargetPoolExecute(r loadbalancerv2api.ApiUpdateTargetPoolRequest) (*loadbalancerv2api.TargetPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTargetPoolExecute", r)
	ret0, _ := ret[0].(*loadbalancerv2api.TargetPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTargetPoolExecute indicates an expected call of UpdateTargetPoolExecute.
func (mr *MockDefaultAPIMockRecorder) UpdateTargetPoolExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTargetPoolExecute", reflect.TypeOf((*MockDefaultAPI)(nil).UpdateTargetPoolExecute), r)
}
